spring:
  application:
    name: ShopCoreAPI

#Data base
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update